# Paste these into Streamlit Community Cloud > App settings > Secrets
SUPABASE_URL = "https://chvblbiabwougqojawuy.supabase.co/rest/v1/"
SUPABASE_SERVICE_KEY = "sb_publishable_Qi6YP1_3nHazqm9HeWie-Zg_3uJ5uYd2"
ADMIN_PASSWORD = "0X03PXj6bW46n25v"
