
-- Run this once in Supabase SQL Editor.
-- The Streamlit app uses the service-role key server-side.
-- Do NOT put the service-role key in your GitHub repository.

create table if not exists players (
  id bigint generated by default as identity primary key,
  name text not null,
  active boolean not null default true
);

create table if not exists events (
  id bigint generated by default as identity primary key,
  name text not null,
  icon text not null default '🎯',
  description text default ''
);

create table if not exists results (
  id bigint generated by default as identity primary key,
  event_id bigint not null references events(id) on delete cascade,
  player_id bigint not null references players(id) on delete cascade,
  score numeric not null default 0,
  points numeric not null default 0,
  created_at timestamptz not null default now()
);

insert into players (name)
select x from unnest(array['J','C','R','P','E','N']) as x
where not exists (select 1 from players);

insert into events (name, icon, description)
select * from (values
  ('Archery','🏹','Bullseyes and pressure.'),
  ('Golf','⛳','18 holes. One leaderboard.'),
  ('Chess','♟️','Checkmate your competition.')
) as v(name, icon, description)
where not exists (select 1 from events);

-- The Streamlit server uses the Supabase service-role key.
-- Public visitors only interact with the Streamlit app, not Supabase directly.
